import { useEffect, useState } from "react";
import axios from "axios";
import { Routes, Route, NavLink, useNavigate } from "react-router-dom";
import { BookOpen, Compass, GraduationCap, Home, ImagePlus, LogIn, MessageSquare, Plus, Shield, Users, X } from "lucide-react";
import "@/App.css";

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;
const api = axios.create({ baseURL: API, withCredentials: true });
const founderData = [{ name: "oildrila", email: "founder-email@edit-me.com", linkedin: "linkedin.com/in/oildrila" }, { name: "Arjun Jha", email: "arjunjha056@edit-me.com", linkedin: "linkedin.com/in/arjunjha056" }];

function formatError(e) { const d=e.response?.data?.detail; return Array.isArray(d)?d.map(x=>x.msg).join(" "):d || "Something went wrong. Try again."; }
function compressImage(file) { return new Promise((resolve,reject)=>{ const reader=new FileReader(); reader.onload=()=>{ const img=new Image(); img.onload=()=>{ const scale=Math.min(1,800/img.width), canvas=document.createElement("canvas"); canvas.width=img.width*scale; canvas.height=img.height*scale; canvas.getContext("2d").drawImage(img,0,0,canvas.width,canvas.height); resolve(canvas.toDataURL("image/jpeg",.6)); }; img.onerror=reject; img.src=reader.result; }; reader.readAsDataURL(file); }); }
function TeacherComposer({onSaved}) { const [topic,setTopic]=useState(""),[details,setDetails]=useState(""); const submit=async e=>{e.preventDefault();if(!topic.trim()||!details.trim())return;await api.post("/teacher-updates",{topic,details});setTopic("");setDetails("");onSaved()}; return <form className="teacher-form" onSubmit={submit} data-testid="teacher-update-form"><input data-testid="teacher-topic-input" placeholder="Today’s topic" value={topic} onChange={e=>setTopic(e.target.value)} required/><textarea data-testid="teacher-details-input" placeholder="What did you teach today?" value={details} onChange={e=>setDetails(e.target.value)} required/><button className="primary-btn compact" data-testid="teacher-update-submit-button">Publish teaching note <Plus size={16}/></button></form> }

function Auth({ onAuth }) { const [mode,setMode]=useState("login"), [form,setForm]=useState({name:"",email:"",password:"",role:"student"}), [error,setError]=useState(""); const submit=async e=>{e.preventDefault();setError("");try{const r=await api.post(`/auth/${mode}`,form);onAuth(r.data)}catch(err){setError(formatError(err))}}; return <main className="auth-page"><section className="auth-visual"><div className="brand-mark"><span>n</span> NSEC / ACADEMIA</div><div><p className="eyebrow">NETAJI SUBHAS ENGINEERING COLLEGE</p><h1>Where campus<br/><em>thinking</em> connects.</h1><p className="hero-note">A private academic network for ideas, people, and the work happening at NSEC.</p></div><div className="campus-strip"><img src="https://images.unsplash.com/photo-1591123120675-6f7f1aae0e5b?crop=entropy&cs=srgb&fm=jpg&q=85" alt="Campus"/><span>Explore the people behind the progress →</span></div></section><section className="auth-panel"><div className="auth-box"><div className="mobile-brand">NSEC / ACADEMIA</div><p className="eyebrow">{mode === "login" ? "WELCOME BACK" : "JOIN THE NETWORK"}</p><h2>{mode === "login" ? "Sign in to your campus." : "Create your campus profile."}</h2><p className="muted">Connect with classmates, teachers, and ideas.</p>{error&&<div className="error" data-testid="auth-error">{error}</div>}<form onSubmit={submit} data-testid="auth-form">{mode === "register"&&<input data-testid="register-name-input" placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/>}<input data-testid="auth-email-input" type="email" placeholder="College email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/><input data-testid="auth-password-input" type="password" placeholder="Password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/>{mode === "register"&&<select data-testid="role-select" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="student">Student</option><option value="teacher">Teacher</option><option value="founder">Founder / Admin</option></select>}<button className="primary-btn" data-testid="auth-submit-button">{mode === "login"?"Enter NSEC":"Create profile"}<LogIn size={17}/></button></form><button className="google-btn" data-testid="google-login-button" onClick={()=>setError("Google login is ready for OAuth configuration by an administrator.")}>G <span>Continue with Google</span></button><button className="text-btn" data-testid="auth-mode-toggle" onClick={()=>{setMode(mode==="login"?"register":"login");setError("")}}>{mode==="login"?"New to NSEC? Create an account":"Already have an account? Sign in"}</button><button className="access-link" data-testid="access-issue-button" onClick={()=>setError("For access issues, contact the NSEC founders from the Info section.")}>Having trouble accessing your account?</button></div></section></main> }

function Shell({user,onLogout}) {
  const [active,setActive]=useState("feed"); const [posts,setPosts]=useState([]); const [rooms,setRooms]=useState([]); const [updates,setUpdates]=useState([]); const [body,setBody]=useState(""); const [image,setImage]=useState("");
  const refresh=()=>{api.get("/feed").then(r=>setPosts(r.data)).catch(()=>{});api.get("/rooms").then(r=>setRooms(r.data)).catch(()=>{});api.get("/teacher-updates").then(r=>setUpdates(r.data)).catch(()=>{})}; useEffect(refresh,[]);
  const publish=async e=>{e.preventDefault();if(!body.trim())return;await api.post("/feed",{body,image});setBody("");setImage("");refresh()}; const file=async e=>{if(e.target.files[0])setImage(await compressImage(e.target.files[0]))};
  return <div className="app-shell"><header className="topbar"><div className="brand-mark"><span>n</span> NSEC / ACADEMIA</div><div className="top-actions"><span className="role-chip"><span className="online-dot"/> {user.role}</span><button data-testid="logout-button" className="icon-btn" onClick={onLogout}><X size={18}/></button></div></header><div className="layout"><aside className="sidebar"><div className="profile-mini"><div className="avatar">{user.name[0]}</div><strong data-testid="current-user-name">{user.name}</strong><small>{user.email}</small><span>{user.relationship}</span></div><nav>{[["feed","Feed",Home],["rooms","Discussion rooms",MessageSquare],["teachers","Teacher updates",GraduationCap],["info","Info & founders",Users]].map(([id,label,Icon])=><button key={id} data-testid={`nav-${id}-button`} className={active===id?"nav-item active":"nav-item"} onClick={()=>setActive(id)}><Icon size={18}/>{label}</button>)}</nav><div className="sidebar-foot"><Shield size={16}/><span>Private NSEC community</span></div></aside><main className="content">
    {active==="feed"&&<><div className="page-head"><div><p className="eyebrow">NSEC COMMUNITY / TODAY</p><h1>Good morning, {user.name.split(" ")[0]}.</h1></div></div><form className="composer" onSubmit={publish} data-testid="post-composer"><div className="avatar small">{user.name[0]}</div><textarea data-testid="post-body-input" placeholder="Share an idea, question, or small win..." value={body} onChange={e=>setBody(e.target.value)}/>{image&&<div className="image-preview"><img src={image} alt="Selected preview"/><button type="button" data-testid="remove-image-button" onClick={()=>setImage("")}><X size={14}/></button></div>}<div className="composer-actions"><label className="attach" data-testid="image-upload-label"><ImagePlus size={17}/> Add image<input data-testid="image-upload-input" type="file" accept="image/*" onChange={file}/></label><button className="primary-btn compact" data-testid="publish-post-button">Publish <Plus size={16}/></button></div></form><div className="feed-list">{posts.map(p=><article className="post" key={p.id} data-testid="feed-post"><div className="post-top"><div className="avatar small">{p.author[0]}</div><div><strong>{p.author}</strong><small>{p.role} · NSEC community</small></div></div><p>{p.body}</p>{p.image&&<img className="post-image" src={p.image} alt="Post attachment"/>}</article>)}</div></>}
    {active==="rooms"&&<Section title="Discussion rooms" eyebrow="OPEN CONVERSATIONS" intro="Find your people around the questions that matter on campus."><div className="room-grid">{rooms.map(r=><article className="room" key={r.id} data-testid="discussion-room"><span className="room-icon"><MessageSquare size={19}/></span><h3>{r.title}</h3><p>{r.description}</p><small>{r.members} members</small></article>)}</div></Section>}
    {active==="teachers"&&<Section title="Teacher updates" eyebrow="WHAT WAS TAUGHT TODAY" intro="Daily notes from the people guiding the next generation of builders.">{(user.role==="teacher"||user.role==="founder")&&<TeacherComposer onSaved={refresh}/>}<div className="updates">{updates.length?updates.map(u=><article className="update" key={u.id} data-testid="teacher-update"><div className="date-tag">TODAY</div><div><strong>{u.topic}</strong><p>{u.details}</p><small>Shared by {u.teacher}</small></div></article>):<div className="empty">No teaching updates yet.</div>}</div></Section>}
    {active==="info"&&<Section title="The people behind NSEC Academia" eyebrow="INFO / ACCESS SUPPORT" intro="A shared space for the NSEC community, shaped by its founders."><div className="founder-grid">{founderData.map(f=><article className="founder" key={f.name} data-testid="founder-card"><div className="founder-photo">{f.name[0]}</div><div><p className="eyebrow">FOUNDER</p><h3>{f.name}</h3><p className="muted">{f.email}</p><p className="linkedin">in&nbsp; {f.linkedin}</p></div></article>)}</div><div className="access-note"><BookOpen size={22}/><div><strong>Need help getting access?</strong><p>Use your college email when registering. For account issues, reach out to a founder.</p></div></div></Section>}
  </main></div></div>
}

function Section({title,eyebrow,intro,children}){return <><div className="page-head section-head"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="muted intro">{intro}</p></div></div>{children}</>}
function App(){const [user,setUser]=useState(null),[checking,setChecking]=useState(true);useEffect(()=>{api.get("/auth/me").then(r=>setUser(r.data)).catch(()=>{}).finally(()=>setChecking(false))},[]);if(checking)return <div className="loading" data-testid="loading-state">Loading NSEC Academia…</div>;return user?<Shell user={user} onLogout={async()=>{await api.post("/auth/logout");setUser(null)}}/>:<Auth onAuth={setUser}/>}
export default function RoutedApp(){return <Routes><Route path="*" element={<App/>}/></Routes>}