export const facultyRoster = [
  { name: "Principal, NSEC", email: "principal@nsec.ac.in", title: "Principal" },
  { name: "Soumava Goswami", email: "soumava.nsec@gmail.com", title: "Faculty" },
  { name: "Ritayan Chatterjee", email: "ritayan.chatterjee@nsec.ac.in", title: "Faculty" },
  { name: "University Affairs", email: "universityaffairs@nsec.ac.in", title: "Administration" },
  { name: "Ananya Ghosh", email: "ananya.ghosh@nsec.ac.in", title: "Faculty" },
];

export const memberRoster = [
  { name: "Saurabh Kumar", email: "saurabhyad780@gmail.com" },
  { name: "Raiyan Ali Khan", email: "raiyanalikhan5@gmail.com" },
  { name: "Souravi Basak", email: "souravibasak2008@gmail.com" },
  { name: "Saumya Dubey", email: "dubeysaumya555@gmail.com" },
  { name: "Kishalay G", email: "kishalayg1@gmail.com" },
  { name: "Suvankar Bhawal", email: "suvankarbhawal8903@gmail.com" },
  { name: "Suraj Prasad Sahoo", email: "surajpsahoo@gmail.com" },
  { name: "Aritra Dey", email: "aritradey636@gmail.com" },
  { name: "Debajyoti Bhattacharyya Riju", email: "debajyotibhattacharyyariju@gmail.com" },
  { name: "Md Yeamin Pwian", email: "skmdyeamin38@gmail.com" },
  { name: "Sam Yadav", email: "yadavsam11222778@gmail.com" },
  { name: "Cyborg MechX", email: "cyborgmechx2018@gmail.com" },
  { name: "Ankita MS", email: "msankita06@gmail.com" },
  { name: "Debanjan Mukherjee", email: "debanjanmukherjee0111@gmail.com" },
  { name: "Sima Ghosh", email: "sima1234ghosh@gmail.com" },
  { name: "Siddharth Ujjwal", email: "sg21111969@gmail.com" },
  { name: "Susanna SM Mukherjee", email: "susannasm.007@gmail.com" },
  { name: "Sakshi Keshri", email: "sakshikeshri9126a00@gmail.com" },
  { name: "Subhajit Roy", email: "roysubhajit3098@gmail.com" },
  { name: "Kandarpa B", email: "kandarpab2020@gmail.com" },
  { name: "Shankhadip Poria", email: "shankhadipporia22@gmail.com" },
  { name: "Arkadip Panja", email: "arkadippanja21@gmail.com" },
  { name: "Avijit Mondal", email: "avijitmondal2k@gmail.com" },
  { name: "Purba De", email: "depurba.wb@gmail.com" },
  { name: "Riddhi Paul", email: "paulriddhi814@gmail.com" },
  { name: "Sayan Bera", email: "sayanbera8710@gmail.com" },
  { name: "Ayushman Mukherjee", email: "ayushmanmukherjee696@gmail.com" },
  { name: "Bidisha Mondal", email: "mondalbidisha.1982@gmail.com" },
  { name: "Shuvam Majhi", email: "shuvammajhi2007sm@gmail.com" },
  { name: "Sneha", email: "marvelsneha22@gmail.com" },
  { name: "Koushik Ghosh", email: "koushikghosh1225@gmail.com" },
  { name: "Sumit Ghosh", email: "sg449740@gmail.com" },
  { name: "Sraboni Dutta Baram", email: "sraboniduttabaram1987@gmail.com" },
  { name: "Diksha Kumari", email: "dikshakumari02913@gmail.com" },
  { name: "Arshad WJ", email: "arshadwj382@gmail.com" },
  { name: "Pranay Agarwala", email: "agarwalapranay87@gmail.com" },
  { name: "Saksham Thakur", email: "sakshamthakur603@gmail.com" },
  { name: "Souradeep Ghara", email: "souradeepghara31@gmail.com" },
  { name: "Aniruddha G", email: "aniruddhag442@gmail.com" },
  { name: "Deep Das Babai", email: "deepdasbabai25@gmail.com" },
  { name: "Sounava Sarkar", email: "sarkarsounava281@gmail.com" },
  { name: "Sanoj Kumar", email: "sanojkumar814133@gmail.com" },
  { name: "Roshni Saha", email: "roshnisaha57@gmail.com" },
  { name: "Mano", email: "manosworld10@gmail.com" },
  { name: "Akash Yadav", email: "classakashyadav6@gmail.com" },
  { name: "Almash Hossain", email: "hossainalmash241@gmail.com" },
  { name: "Sibnath Khan", email: "sibnathkhan07@gmail.com" },
  { name: "Utsab Singha", email: "utsabs087@gmail.com" },
  { name: "Nur Parvez Alam", email: "nurparvezalam@gmail.com" },
  { name: "Sahil Jha", email: "sahilvjha12@gmail.com" },
  { name: "Arijit Sikari", email: "arijitsikari7@gmail.com" },
  { name: "Sohini Chanda", email: "chandasohini666@gmail.com" },
  { name: "A Jha", email: "ajha44272@gmail.com" },
  { name: "Purabi Pramanik", email: "purabipramanik148@gmail.com" },
  { name: "Debarghya Dey", email: "debarghyadeyco876@gmail.com" },
  { name: "Ayan Saha", email: "ayansaha1018@gmail.com" },
  { name: "Shambhu Prasad", email: "prasadshambhu088@gmail.com" },
  { name: "Mriganka Mouli Ghosh", email: "mrigankamoulighosh12123232@gmail.com" },
  { name: "Swapnojit Sarkar", email: "swapnojitsarkar8@gmail.com" },
  { name: "Sumit Barik", email: "bariksumit026@gmail.com" },
  { name: "Zaib Siddiqui", email: "siddiquizaib2006@gmail.com" },
  { name: "Amibiva Halder", email: "amibivahalder@gmail.com" },
  { name: "Anirban Adhikary", email: "anirbanadhikary368@gmail.com" },
  { name: "Rajat Pathak", email: "rajatpathak.in@gmail.com" },
  { name: "Keshav", email: "keshav12241@gmail.com" },
  { name: "Titiksha Biswas", email: "biswastitiksha70@gmail.com" },
  { name: "Soumyojit Naskar", email: "simanaskar9674@gmail.com" },
  { name: "Trishita Maity", email: "writetotrishita007@gmail.com" },
  { name: "Umang Kumar", email: "umangkumar506@gmail.com" },
  { name: "Shreyas Pandey", email: "shreyaspandey278@gmail.com" },
  { name: "Upasana Mondal", email: "upasana.mondal.wb@gmail.com" },
  { name: "Naitik Yadav", email: "naitiky2005@gmail.com" },
  { name: "Anurag Daw", email: "chutku9231@gmail.com" },
  { name: "Pratyush Bera", email: "berapratyush4@gmail.com" },
  { name: "Rupesh Thakur", email: "91rupeshthakur@gmail.com" },
  { name: "Sarbajit Majumder", email: "sarbajit2007@gmail.com" },
  { name: "Rika Matsuda", email: "rikamatsuda9373@gmail.com" },
  { name: "Smita Tiwary", email: "tiwarysmita96@gmail.com" },
  { name: "Debanjan Kundu", email: "mr.debanjan.kundu@gmail.com" },
  { name: "Manjit Pandey", email: "manjitpandey412@gmail.com" },
];
